server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: com.hanbo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring
spring:
  application:
    name: springcloud-provider-dept # 集群，名称一致是前提
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111

# eureka, 服务注册到
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 # 修改eureka上默认描述信息
    prefer-ip-address: true # 为true显示服务ip地址

# info配置
info:
  app.name: hanbo-springcloud
  company.name: 121212
